version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
    networks:
      - backend
  mysql:
    image: mysql:8
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=alabala
      - MYSQL_PASSWORD=userpwd
      - MYSQL_USER=user
      - MYSQL_DATABASE=customers
  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    networks:
      - backend
      - frontend
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
volumes:
  my-db:
networks:
  backend:
  frontend: